spring:
  config:
    import: "optional:configtree:/run/secrets/"
  application:
    name: mongodb
  data:
    mongodb:
      uri: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@${MONGO_HOST}:27017/${MONGO_DB}?authSource=admin
discord:
  token: ${DISCORD_TOKEN}
  admin:
    id: ${DISCORD_ADMIN_ID}
    username: ${DISCORD_ADMIN_USERNAME}
portainer:
  base-url: ${PORTAINER_VIRTUAL_HOST}
  token: ${PORTAINER_TOKEN}
