name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Java (Maven environment)
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Step 3: Extract version from pom.xml
    - name: Extract version from pom.xml
      id: extract_version
      run: |
        VERSION=$(xmllint --xpath "string(//project/version)" pom.xml)
        echo "Image version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    # Step 4: Log in to Docker Hub
    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Build the Docker image with the version tag
    - name: Build Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/spring-boot-app
        docker build -t $IMAGE_NAME:${{ env.VERSION }} -t $IMAGE_NAME:latest .

    # Step 6: Push the Docker image with the version tag
    - name: Push Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/spring-boot-app
        docker push $IMAGE_NAME:${{ env.VERSION }}
        docker push $IMAGE_NAME:latest
